from setuptools import setup, find_packages

setup(
    name="GNoME",
    version="0.1.0",
    description="Graph Networks for Materials Exploration",
    author="IMSS",
    author_email="brandonyee.nyc@gmail.com",
    packages=find_packages(),
    install_requires=[
        "absl-py",
        "attrs",
        "cachetools",
        "certifi>=2024.2.2",
        "charset-normalizer",
        "chex",
        "dm-haiku",
        "e3nn-jax",
        "flax",
        "jax",
        "jax-md",
        "jaxlib",
        "jraph",
        "ml-collections",
        "optax",
        "pymatgen",
        "tqdm",
        "matplotlib",
        "networkx",
        "pandas",
        "scipy",
        "seaborn",
    ],
    python_requires=">=3.8",
)